@props(['src', 'alt' => '', 'loading' => 'lazy'])
@php
    // Serve a WebP version to browsers that support it, falling back to the
    // original file. The .webp sibling is generated by `php artisan images:optimize`.
    $webp = preg_replace('/\.(png|jpe?g)$/i', '.webp', $src);
@endphp
<picture>
    <source srcset="{{ $webp }}" type="image/webp">
    <img src="{{ $src }}" alt="{{ $alt }}" loading="{{ $loading }}" {{ $attributes }}>
</picture>
